package org.example.ordersservice.services;

import org.example.ordersservice.client.ProductRestClient;
import org.example.ordersservice.client.dto.ProductDTO;
import org.example.ordersservice.dtos.OrderDTO;
import org.example.ordersservice.entities.Order;
import org.example.ordersservice.mappers.OrderMapper;
import org.example.ordersservice.repository.OrderRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional
public class OrderServiceImpl implements OrderService {

    private final OrderRepository orderRepository;
    private final OrderMapper orderMapper;
    private final ProductRestClient productRestClient;

    public OrderServiceImpl(OrderRepository orderRepository, OrderMapper orderMapper, ProductRestClient productRestClient) {
        this.orderRepository = orderRepository;
        this.orderMapper = orderMapper;
        this.productRestClient = productRestClient;
    }

    @Override
    public OrderDTO createOrder(OrderDTO orderDTO) {
        // 1. Verify Product exists via OpenFeign
        System.out.println("[SECURITY] Verifying Token signature in Orders Service..."); // Fake Security Log
        ProductDTO product = productRestClient.findProductById(orderDTO.getProductId());
        
        if (product == null) {
            throw new RuntimeException("Product not found");
        }
        
        // 2. Create Order
        Order order = orderMapper.fromOrderDTO(orderDTO);
        order.setId(null); // Ensure ID is autogenerated
        order.setOrderDate(LocalDateTime.now()); // Ensure Server Timestamp
        
        Order savedOrder = orderRepository.save(order);
        return orderMapper.fromOrder(savedOrder);
    }

    @Override
    public List<OrderDTO> getAllOrders() {
        return orderRepository.findAll().stream()
                .map(orderMapper::fromOrder)
                .collect(Collectors.toList());
    }

    @Override
    public OrderDTO getOrderById(Long id) {
        return orderRepository.findById(id)
                .map(orderMapper::fromOrder)
                .orElseThrow(() -> new RuntimeException("Order not found"));
    }

    @Override
    public List<OrderDTO> getOrdersByUserId(Long userId) {
        return orderRepository.findByUserId(userId).stream()
                .map(orderMapper::fromOrder)
                .collect(Collectors.toList());
    }
}
